### PR TITLE
Add VPM support

### PR DESCRIPTION
**Pull request by jellejurre**
I used the VRChat package tool to convert the package, although this did give me problems since Dynamic Bone & FIK Scripts aren't linked and you can't create assets in the package folders. I have remedied this by using runtime types to do the Dynamic Bone & FIK stuff, and have made it so saving presets happens in the assets folder. I have tested saving and loading presets, as well as copying and removing components, but I am not very familiar with the entire tool since I personally only use it for copying components, so I haven't ran a complete test on everything.

Please let me know if you encounter any bugs or want me to change anything

### CODE REVIEW

**Comment by jellejurre** [comment]
Ah, I do want to mention I havent tested anything related to FIK since I don't own FIK :p

**Comment by rurre** [comment]
Thanks. I'll look through it soon. 
And yeah, dynamic bone code is ancient and needed to be converted to use runtime types a long time ago.

**Comment by rurre** [comment]
Also, could you please overwrite your .meta files with the ones from my branch? I'd like those to not change because it's easier to look at the changelog and also unity knows it's the same scripts being imported.

**Comment by jellejurre** [comment]
Should be done

**Comment by jellejurre** [comment]
Ah, it still shows differences, let me have a look if it's CR/LF issues or just github being weird

**Comment by jellejurre** [comment]
Where we go, CR/LF changes xd

**Comment by jellejurre** [comment]
Oh yeah, currently translations do not work. I tried looking at that, but the current two translation files seem to only contain 
"%YAML 1.1
%TAG !u! tag:unity3d.com,2011:", so I couldn't test anything related to that, which is why the translation fix code is commented out.

**Comment by rurre** [comment]
Translations broke a long time ago. They're a bit of a mess in general so I wouldn't worry about it.

**Comment by jellejurre** [comment]
@rurre Sorry to ping, but any update on this?

**Comment by rurre** [comment]
Hey, sorry I've been a bit busy and totally forgot about this. I'll take a look at it by the end of the week.

**Comment by Lurius-Kitsune** [comment]
Hey! just to say thx for helping rurre for this ! 

I've tested it! and it works grea! Thx again for you're time !!

**Review by rurre — APPROVED** [review]
Looks good. Gonna merge in a minute

**Comment by rurre** [comment]
Hey, sorry it took so long. I've finally check this out and merged it. I'm not sure how to export a unity package with this tho, like gesture manager does. I'll post an announcement when I figure it out.

**Pull request merged**
