### PR TITLE
Add new dynamic physbones and contacts

### PR DESCRIPTION
**Pull request by Shiroe2**
*Compatible with both live and open beta SDKs
*Includes Imagitama's Pull Request: Create missing transforms option #49
*Moved transform copier above everything else to fix skinned meshes not moving

### CODE REVIEW

**Comment by rurre** [comment]
Thanks, I'll take a look at it and try to release it later today.

**Comment by NotAKidOnSteam** [comment]
Please also include the custom collision set in the Avatar Descriptor.
image

it can be one of the more annoying things to copy manually...
image

**Review by rurre — APPROVED** [review]
Looks good! But I think we don't need a #if PUMKIN_PBONES precompiler directive since pbones come with the vrchat sdk. Will leave it for now so both beta sdk and live sdk is supported.

**Comment by Shiroe2** [comment]
@rurre when do you think your next planned release is?

**Comment by rurre** [comment]
Probably until avatar dynamics goes live.
There are little changes happening now but I'd like to allow more time for people to test stuff.
________________________________

**Pull request merged**
